# Tirando conclusões usando query

In [2]:
# Carregue o arquivo `winequality_edited.csv`
import pandas as pd
import numpy as np

df_wine = pd.read_csv('winequality_edited.csv')
df_wine.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [3]:
# Printando a coluna alcohol
df_wine['alcohol'].describe()

count    6497.000000
mean       10.491801
std         1.192712
min         8.000000
25%         9.500000
50%        10.300000
75%        11.300000
max        14.900000
Name: alcohol, dtype: float64

### Será que vinhos com maior teor alcóolico recebem avaliações melhores?

In [17]:
# Obtendo o valor mediano do teor alcóolico
alcohol_median = df_wine['alcohol'].median()
alcohol_median

10.3

In [5]:
# Obtendo a mediana de df_wine
df_wine.median()

fixed_acidity             7.00000
volatile_acidity          0.29000
citric_acid               0.31000
residual_sugar            3.00000
chlorides                 0.04700
free_sulfur_dioxide      29.00000
total_sulfur_dioxide    118.00000
density                   0.99489
pH                        3.21000
sulphates                 0.51000
alcohol                  10.30000
quality                   6.00000
dtype: float64

In [20]:
# Selecionando amostras com teor alcóolico abaixo da mediana
low_alcohol = df_wine.query('alcohol < @alcohol_median')
low_alcohol.head(10)

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5,red
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,5,red
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,7,red
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,7,red
10,6.7,0.58,0.08,1.8,0.097,15.0,65.0,0.9959,3.28,0.54,9.2,5,red

In [21]:
# Selecionando amostras com teor alcóolico maior ou igual à mediana
high_alcohol = df_wine.query('alcohol >= @alcohol_median')
high_alcohol.head(10)

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,color
9,7.5,0.500,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5,red
11,7.5,0.500,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5,red
16,8.5,0.280,0.56,1.8,0.092,35.0,103.0,0.9969,3.30,0.75,10.5,7,red
31,6.9,0.685,0.00,2.5,0.105,22.0,37.0,0.9966,3.46,0.57,10.6,6,red
36,7.8,0.600,0.14,2.4,0.086,3.0,15.0,0.9975,3.42,0.60,10.8,6,red
39,7.3,0.450,0.36,5.9,0.074,12.0,87.0,0.9978,3.33,0.83,10.5,5,red
40,7.3,0.450,0.36,5.9,0.074,12.0,87.0,0.9978,3.33,0.83,10.5,5,red
42,7.5,0.490,0.20,2.6,0.332,8.0,14.0,0.9968,3.21,0.90,10.5,6,red
43,8.1,0.660,0.22,2.2,0.069,9.0,23.0,0.9968,3.30,1.20,10.3,5,red
45,4.6,0.520,0.15,2.1,0.054,8.0,65.0,0.9934,3.90,0.56,13.1,4,red

In [22]:
# Certificando que estas consultas incluíram cada amostra uma única vez
num_samples = df_wine.shape[0]
num_samples == low_alcohol['quality'].count() + high_alcohol['quality'].count() # resultado deve ser True

True

In [25]:
# Obter a avaliação média de qualidade para grupos com alto e baixo teor alcóolico
print(" Avaliação média para alto teor:{0} \n Avaliação média para baixo teor:{1}".format(
        high_alcohol["quality"].mean(), low_alcohol["quality"].mean() ))

 Avaliação média para alto teor:6.146084337349397
 Avaliação média para baixo teor:5.475920679886686

### Vinhos mais suaves recebem avaliações melhores?

In [26]:
# Obter o valor mediano do nível de açúcar residual
residual_median = df_wine['residual_sugar'].median()
residual_median

3.0

In [27]:
# Selecionar amostras com nível de açúcar residual abaixo da mediana
low_sugar = df_wine.query('residual_sugar < @residual_median')
low_sugar.head(10)

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5,red
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,5,red
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,7,red
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,7,red
10,6.7,0.58,0.08,1.8,0.097,15.0,65.0,0.9959,3.28,0.54,9.2,5,red

In [28]:
# selecione amostras com nível de açúcar residual maior ou igual à mediana
high_sugar = df_wine.query('residual_sugar >= @residual_median')
high_sugar.head(10)

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,color
9,7.5,0.500,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5,red
11,7.5,0.500,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5,red
14,8.9,0.620,0.18,3.8,0.176,52.0,145.0,0.9986,3.16,0.88,9.2,5,red
15,8.9,0.620,0.19,3.9,0.170,51.0,148.0,0.9986,3.17,0.93,9.2,5,red
18,7.4,0.590,0.08,4.4,0.086,6.0,29.0,0.9974,3.38,0.50,9.0,4,red
33,6.9,0.605,0.12,10.7,0.073,40.0,83.0,0.9993,3.45,0.52,9.4,6,red
35,7.8,0.645,0.00,5.5,0.086,5.0,18.0,0.9986,3.40,0.55,9.6,6,red
39,7.3,0.450,0.36,5.9,0.074,12.0,87.0,0.9978,3.33,0.83,10.5,5,red
40,7.3,0.450,0.36,5.9,0.074,12.0,87.0,0.9978,3.33,0.83,10.5,5,red
53,8.6,0.380,0.36,3.0,0.081,30.0,119.0,0.9970,3.20,0.56,9.4,5,red

In [13]:
# Certificar que estas consultas incluíram cada amostra uma única vez
num_samples == low_sugar['quality'].count() + high_sugar['quality'].count() # resultado deve ser True

True

In [14]:
# Obter a avaliação média de qualidade para grupos com alto e baixo nível de açúcar residual
print(" Avaliação média para alto nível:{0} \n Avaliação média para baixo nivel:{1}".format(high_sugar['quality'].mean(), low_sugar['quality'].mean()))

 Avaliação média para alto nível:5.82782874617737
 Avaliação média para baixo nivel:5.808800743724822

In [29]:
high_sugar['quality'].mean(), low_sugar['quality'].mean()

(5.82782874617737, 5.808800743724822)